Repository desmos-labs/dpm, pull requests merged in 2023-07, with the labels that each got.

#205 refactor: update landing page design
  src/assets/images/applications/discord.png
  src/assets/images/applications/github.png
  src/assets/images/applications/google.png
  src/assets/images/applications/linkedin.png
  src/assets/images/applications/reddit.png
  src/assets/images/applications/twitch.png
  src/assets/images/applications/twitter.png
  src/assets/images/applications/wechat.png
  src/assets/images/applications/weibo.png
  src/assets/locales/en/landing.json
  src/components/Typography/config.ts
  src/components/Typography/index.tsx
  src/modals/ModalScreen/useStyles.ts
  src/modals/SingleButtonModal/index.tsx
  src/modals/SingleButtonModal/useStyles.ts
  src/modals/Web3AuthLoginProvidersModal/components/LoginProviderListItem/index.tsx
  src/modals/Web3AuthLoginProvidersModal/components/LoginProviderListItem/useStyles.ts
  src/modals/Web3AuthLoginProvidersModal/index.tsx
  src/modals/Web3AuthLoginProvidersModal/useStyles.ts
  src/screens/Landing/index.tsx
  src/screens/Landing/useStyles.ts
Labels: automerge

#207 feat: new bottom bar design
  src/assets/images/icons/apps.png
  src/assets/images/icons/appsGray.png
  src/assets/images/icons/home.png
  src/assets/images/icons/homeGray.png
  src/assets/images/icons/iconModuleCosmWasmGray.png
  src/assets/images/icons/iconModuleGovernanceGray.png
  src/assets/images/index.ts
  src/assets/images/scanQRButton.png
  src/assets/locales/en/governance.json
  src/assets/locales/en/index.ts
  src/components/Typography/config.ts
  src/components/Typography/index.tsx
  src/navigation/RootNavigator/HomeTabs/components/BottomBar/index.tsx
  src/navigation/RootNavigator/HomeTabs/components/BottomBar/useStyles.ts
  src/navigation/RootNavigator/HomeTabs/components/BottomBarIcon/index.tsx
  src/navigation/RootNavigator/HomeTabs/components/TabIcons/AuthorizationTabIcon.tsx
  src/navigation/RootNavigator/HomeTabs/components/TabIcons/HomeTabIcon.tsx
  src/navigation/RootNavigator/HomeTabs/components/TabIcons/ScanQrTabIcon.tsx
  src/navigation/RootNavigator/HomeTabs/components/TabIcons/index.ts
  src/navigation/RootNavigator/HomeTabs/index.tsx
  src/navigation/RootNavigator/HomeTabs/props.ts
  src/navigation/RootNavigator/index.tsx
  src/navigation/routes.ts
  src/screens/GovernanceProposals/index.tsx
  src/screens/GovernanceProposals/useStyles.ts
  src/screens/Home/components/AccountBalances/index.tsx
  src/screens/Home/index.tsx
  src/screens/ManageStaking/index.tsx
  src/screens/WalletConnectSessions/index.tsx
  src/screens/WalletConnectSessions/useStyles.ts
Labels: C: UI, automerge

#208 feat: add proposal list screen
  package.json
  src/assets/locales/en/governance.json
  src/components/Badge/index.tsx
  src/components/Badge/props.ts
  src/components/Badge/useStyles.ts
  src/components/ProposalStatusBadge/index.tsx
  src/components/Typography/config.ts
  src/components/Typography/index.tsx
  src/config/theme/LightTheme.ts
  src/config/theme/customTheme.d.ts
  src/lib/FormatUtils/index.test.ts
  src/lib/FormatUtils/index.ts
  src/screens/GovernanceProposals/components/ProposalListItem/index.tsx
  src/screens/GovernanceProposals/components/ProposalListItem/useStyles.ts
  src/screens/GovernanceProposals/hooks.ts
  src/screens/GovernanceProposals/index.tsx
  src/services/graphql/queries/GetProposals.ts
  src/services/graphql/queries/fragments/ProposalFields.ts
  src/types/proposals.ts
  yarn.lock
Labels: Type: Enhancement, automerge

#209 feat: proposal details visualization
  package.json
  src/assets/locales/en/common.json
  src/assets/locales/en/governance.json
  src/assets/locales/en/messages/common.json
  src/assets/locales/en/messages/index.ts
  src/assets/locales/en/messages/staking.json
  src/assets/locales/en/messages/upgrade.json
  src/components/Button/index.tsx
  src/components/Button/props.ts
  src/components/ContentLoaders/Typography/index.tsx
  src/components/Messages/components.ts
  src/components/Messages/staking/MsgUpdateParams/index.tsx
  src/components/Messages/upgrade/v1beta1/MsgSoftwareUpgrade/index.tsx
  src/components/Messages/upgrade/v1beta1/SoftwareUpgradeProposal/index.tsx
  src/components/ProgressBar/index.tsx
  src/components/ProgressBar/useStyles.ts
  src/components/StyledMarkdown/index.tsx
  src/components/StyledMarkdown/useStyles.ts
  src/components/StyledSafeAreaView/index.tsx
  src/components/ThemedTabBar/index.tsx
  src/components/ThemedTabBar/useStyles.ts
  src/config/theme/DarkTheme.ts
  src/config/theme/LightTheme.ts
  src/config/theme/customTheme.d.ts
  src/hooks/messages/useMessageName.ts
  src/hooks/staking/useTotalRedelegatingAmount.ts
  src/lib/GraphQLUtils/message.ts
  src/navigation/RootNavigator/index.tsx
  src/navigation/routes.ts
  src/screens/GovernanceProposalDetails/components/ActiveProposalHeader/index.tsx
  src/screens/GovernanceProposalDetails/components/ActiveProposalHeader/useStyles.ts
  src/screens/GovernanceProposalDetails/components/CompletedProposalHeader/index.tsx
  src/screens/GovernanceProposalDetails/components/CompletedProposalHeader/useStyles.ts
  src/screens/GovernanceProposalDetails/components/ProposalDetails/index.tsx
  src/screens/GovernanceProposalDetails/components/VoteListItem/index.tsx
  src/screens/GovernanceProposalDetails/components/VoteListItem/useStyles.ts
  src/screens/GovernanceProposalDetails/components/Votes/hooks.ts
  src/screens/GovernanceProposalDetails/components/Votes/index.tsx
  src/screens/GovernanceProposalDetails/index.tsx
  src/screens/GovernanceProposalDetails/useStyles.ts
  src/screens/GovernanceProposals/index.tsx
  src/screens/ManageStaking/tabs/Restaking/hooks.ts
  src/screens/ManageStaking/tabs/Staked/hooks.ts
  src/screens/ManageStaking/tabs/Unbonding/hooks.ts
  src/services/graphql/queries/GetProposalVotes.ts
  src/services/graphql/queries/GetValidatorInfo.ts
  src/services/graphql/queries/fragments/ProposalFields.ts
  src/types/cosmos.ts
  src/types/proposals.ts
  yarn.lock
Labels: Type: Enhancement, automerge

#212 feat: remove amount from transactions list items where not necessary
  src/hooks/messages/useGetMessageAmount.ts
  src/screens/Home/components/TransactionsListItem/index.tsx
Labels: C: UI, automerge

#213 feat: hide vertical scroll indicator in the home screen
  src/screens/Home/index.tsx
Labels: C: UI, automerge

#214 feat: made the entire element of a RadioGroup clickable
  src/components/RadioGroup/index.tsx
Labels: C: UI, automerge

#217 fix: MsgExec description
  package.json
  src/assets/locales/en/messages/authz.json
  src/components/Messages/authz/MsgExecDetails/index.tsx
  yarn.lock
Labels: C: UI, automerge

#218 fix: components shadows on iOS
  ios/DesmosProfileManager.xcodeproj/project.pbxproj
  ios/Podfile.lock
  src/components/DpmTabBar/index.tsx
  src/components/DpmTabBar/useStyles.ts
  src/components/StyledRefreshControl/index.tsx
  src/config/theme/LightTheme.ts
  src/config/theme/customTheme.d.ts
  src/navigation/RootNavigator/HomeTabs/components/BottomBar/useStyles.ts
  src/screens/GovernanceProposalDetails/components/Votes/index.tsx
  src/screens/GovernanceProposals/index.tsx
  src/screens/Home/components/AccountBalancesAction/useStyles.ts
  src/screens/Home/index.tsx
  src/screens/Home/useStyles.ts
  src/screens/ImportAccountSelectType/components/ImageButton/useStyles.ts
  src/screens/ManageStaking/index.tsx
  src/screens/ManageStaking/tabs/Restaking/index.tsx
  src/screens/ManageStaking/tabs/Staked/index.tsx
  src/screens/ManageStaking/tabs/Unbonding/index.tsx
  src/screens/PerformLedgerScan/components/LedgerDeviceList/index.tsx
  src/screens/PerformLedgerScan/components/LedgerDeviceList/useStyles.ts
  src/screens/Profile/index.tsx
  src/screens/SelectAccount/components/PaginatedFlatList/index.tsx
  src/screens/SelectValidator/index.tsx
  src/screens/WalletConnectSessions/components/SessionListItem/useStyles.ts
  src/screens/WalletConnectSessions/components/SessionsList/index.tsx
  src/screens/WalletConnectSessions/components/SessionsList/useStyles.ts
Labels: C: UI, P: iOS, automerge

#219 fix: application crash when deleting the last account
  src/hooks/staking/useAccountPendingStakingRewards.ts
  src/hooks/staking/useTotalDelegatedAmount.ts
  src/hooks/staking/useTotalRedelegatingAmount.ts
  src/hooks/staking/useTotalUnbondingAmount.ts
Labels: Type: Bug, C: Logic, automerge

#220 feat: show privacy policy and tos from desmos site
  android/app/src/main/assets/custom/privacy.md
  android/app/src/main/assets/custom/tos.md
  android/link-assets-manifest.json
  assets/md/privacy.md
  assets/md/tos.md
  ios/DesmosProfileManager.xcodeproj/project.pbxproj
  ios/link-assets-manifest.json
  src/hooks/legal/useShowPrivacyPolicy.ts
  src/hooks/legal/useShowToS.ts
Labels: C: Logic, automerge

#221 feat: use new image in SelectNewMnemonicLength screen
  src/assets/images/index.ts
  src/assets/images/mnemonic.png
  src/components/DPMImage/index.tsx
  src/screens/SelectNewMnemonicLength/index.tsx
  src/types/images.ts
Labels: C: UI, automerge

#222 feat: add modal that explain what data the application collects
  src/assets/locales/en/settings.json
  src/modals/ModalScreen/useStyles.ts
  src/screens/Settings/hooks.ts
  src/screens/Settings/index.tsx
Labels: C: UI, automerge

#195 feat: improve analytics
  src/components/DesmosPostHogProvider/index.tsx
  src/components/FeatureFlags/index.ts
  src/hooks/analytics/useIsTestnetEvent.ts
  src/hooks/analytics/useIsTestnetTransaction.ts
  src/hooks/analytics/useTrackAppOpened.ts
  src/hooks/analytics/useTrackEvent.ts
  src/hooks/analytics/useTrackNewAccountAdded.ts
  src/hooks/analytics/useTrackScreen.ts
  src/hooks/analytics/useTrackTransactionPerformed.ts
  src/hooks/analytics/useTrackWalletConnectSessionEstablished.ts
  src/hooks/analytics/useTransactionProperties.ts
  src/hooks/staking/useTotalRedelegatingAmount.ts
  src/screens/BroadcastTx/hooks.ts
  src/screens/BroadcastTx/index.tsx
  src/screens/DevScreen/index.tsx
  src/screens/EditProfile/index.tsx
  src/screens/Profile/index.tsx
  src/screens/SendTokens/index.tsx
  src/types/analytics.ts
  src/types/appFeatureFlags.ts
Labels: Type: Enhancement, C: Logic

#225 ci: update iOS provisioning profiles
  ios/DesmosProfileManager.xcodeproj/project.pbxproj
Labels: automerge

#227 fix: reset to landing page during import with Web3Auth
  src/hooks/useLoginWithWeb3Auth.ts
Labels: Type: Bug, C: Logic, automerge

#226 feat: handle corrupted keychain
  src/App.tsx
  src/assets/locales/en/common.json
  src/assets/locales/en/dataIntegrity.json
  src/assets/locales/en/index.ts
  src/hooks/dataintegrity/useCheckKeyChainIntegrity.ts
  src/hooks/navigation/useResetToScreen.ts
  src/lib/SecureStorage/index.ts
  src/modals/CorruptedKeychainModal/hooks.ts
  src/modals/CorruptedKeychainModal/index.tsx
  src/modals/CorruptedKeychainModal/useStyles.ts
  src/modals/ModalScreen/index.tsx
  src/modals/SingleButtonModal/index.tsx
  src/recoil/accounts.ts
  src/recoil/applicationLinks.ts
  src/recoil/chainLinks.ts
  src/recoil/profiles.ts
  src/screens/DevScreen/index.tsx
Labels: Type: Enhancement, C: Logic, automerge

#228 feat: allow to search a recipient of a token send by their dtag or nickname
  src/assets/locales/en/sendTokens.json
  src/components/ProfileListItem/index.tsx
  src/components/ProfileListItem/useStyles.ts
  src/components/StyledSafeAreaView/index.tsx
  src/components/TextInput/index.tsx
  src/components/TextInput/useStyles.ts
  src/screens/SendTokens/components/RecipientsList/hooks.ts
  src/screens/SendTokens/components/RecipientsList/index.tsx
  src/screens/SendTokens/components/RecipientsList/useStyles.ts
  src/screens/SendTokens/index.tsx
  src/services/graphql/queries/GetProfilesFromNickNameOrDtagOrAddress.ts
Labels: Type: Enhancement, C: UI, automerge

#229 feat: select token amount based on fiat value
  src/assets/images/icons/currencyDSM.png
  src/assets/images/icons/currencyUSD.png
  src/assets/images/index.ts
  src/assets/locales/en/components/coinAmountInput.json
  src/components/CoinAmountInput/hooks.ts
  src/components/CoinAmountInput/index.tsx
  src/components/CoinAmountInput/useStyles.ts
  src/hooks/balance/useCoinsFiatAmouont.ts
  src/hooks/balance/useTokensPrices.ts
  src/lib/FormatUtils/index.ts
  src/screens/Home/components/AccountBalances/index.tsx
  src/screens/SendTokens/index.tsx
  src/types/prices.ts
Labels: Type: Enhancement, C: Logic, automerge

#230 feat: address qr code
  package.json
  src/assets/images/icons/qrCode.png
  src/assets/images/index.ts
  src/assets/locales/en/common.json
  src/components/CopyButton/index.tsx
  src/components/CopyButton/useStyles.ts
  src/components/IconButton/index.tsx
  src/modals/ModalScreen/useStyles.ts
  src/modals/QRCodeAddressModal/index.tsx
  src/modals/QRCodeAddressModal/useStyles.ts
  src/screens/Home/components/AccountBalances/index.tsx
  src/screens/Home/components/AccountBalances/useStyles.ts
  yarn.lock
Labels: Type: Enhancement, C: Logic, automerge
