Repository desmos-labs/dpm, pull requests merged in 2023-11, with the labels that each got.

#255 refactor: replace KeyboardAvoidingView with DKeyboardAvoidingView
  src/screens/CheckWalletPassword/index.tsx
  src/screens/CreateWalletPassword/index.tsx
  src/screens/EditProfile/index.tsx
  src/screens/ImportAccountFromMnemonic/index.tsx
  src/screens/SettingsChangeWalletPassword/index.tsx
  src/screens/SettingsEnableBiometricsAuthorization/index.tsx
  src/screens/UnlockApplication/index.tsx
  src/screens/UnlockWallet/index.tsx
Labels: Type: Enhancement, C: Logic, automerge

#254 refactor: update modal behavior
  src/modals/AmountAndMemoModal/index.tsx
  src/modals/AmountAndMemoModal/useStyles.ts
  src/modals/ModalScreen/index.tsx
Labels: Type: Bug, C: UI, automerge

#256 fix: inline code not displayed when converting markdown text to plaintext
  src/lib/FormatUtils/index.ts
  src/screens/GovernanceProposalDetails/components/ProposalDetails/index.tsx
Labels: Type: Bug, C: UI, automerge

#250 feat: allow to disable the password prompt at application open and resume
  src/assets/locales/en/settings.json
  src/components/Flexible/SectionSwitch/index.tsx
  src/hooks/useLockApplicationOnBlur.ts
  src/modals/TwoButtonModal/index.tsx
  src/navigation/RootNavigator/index.tsx
  src/navigation/routes.ts
  src/recoil/settings.ts
  src/screens/Settings/hooks.ts
  src/screens/Settings/index.tsx
  src/screens/SettingsSwitchScreen/index.tsx
  src/screens/SettingsSwitchScreen/useStyles.ts
  src/types/settings.ts
Labels: Type: Enhancement, C: UI, C: Logic, automerge

#257 fix: gas adjustment
  src/screens/BroadcastTx/hooks.ts
Labels: Type: Bug, C: UI

#258 feat: keep wallet unlocked after first unlock
  src/hooks/useUnlockWallet.ts
  src/lib/WalletUtils/generate.ts
  src/recoil/wallet.ts
  src/screens/UnlockWallet/useHooks.ts
  src/types/wallet.ts
Labels: C: Logic, automerge

#259 fix: proposal details scroll
  package.json
  src/components/Spacer/index.tsx
  src/components/StyledSafeAreaView/index.tsx
  src/components/TabBar/MaterialTabBar/TabItem.tsx
  src/components/TabBar/MaterialTabBar/index.tsx
  src/components/ThemedTabBar/index.tsx
  src/components/ThemedTabBar/useStyles.ts
  src/hooks/usePaginatedData.ts
  src/screens/GovernanceProposalDetails/components/ActiveProposalHeader/index.tsx
  src/screens/GovernanceProposalDetails/components/CompletedProposalHeader/index.tsx
  src/screens/GovernanceProposalDetails/components/ProposalDetails/index.tsx
  src/screens/GovernanceProposalDetails/components/Votes/hooks.ts
  src/screens/GovernanceProposalDetails/components/Votes/index.tsx
  src/screens/GovernanceProposalDetails/index.tsx
  src/screens/GovernanceProposalDetails/useStyles.ts
  yarn.lock
Labels: Type: Bug, C: UI, P: iOS, automerge

#260 feat: improve proposal details visualization
  src/assets/locales/en/common.json
  src/assets/locales/en/messages/common.json
  src/components/InlineProfile/index.tsx
  src/components/Messages/MessageDetails.tsx
  src/components/Messages/common/MsgUpdateParamsDetails/index.tsx
  src/components/Messages/components.ts
  src/components/Messages/staking/MsgUpdateParams/index.tsx
  src/components/Messages/tokenfactory/MsgUpdateParamsDetails/index.tsx
  src/lib/FormatUtils/index.ts
  src/lib/GraphQLUtils/message.ts
  src/screens/GovernanceProposalDetails/components/ProposalDetails/index.tsx
  src/services/graphql/queries/fragments/ProposalFields.ts
  src/types/proposals.ts
Labels: Type: Enhancement, C: UI, automerge

#261 feat: use the new safe area context lib
  ios/DesmosProfileManager.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  src/components/DKeyboardAvoidingView/index.tsx
  src/components/ProfileHeader/index.tsx
  src/components/StyledSafeAreaView/index.tsx
  src/components/StyledSafeAreaView/useStyles.ts
  src/components/TopBar/useStyles.ts
  src/config/theme/DarkTheme.ts
  src/config/theme/LightTheme.ts
  src/screens/DevScreen/index.tsx
  src/screens/EditProfile/index.tsx
  src/screens/EditProfile/useStyles.ts
  src/screens/GovernanceProposalDetails/index.tsx
  src/screens/GovernanceProposalDetails/useStyles.ts
  src/screens/GovernanceProposals/index.tsx
  src/screens/Home/components/AppDrawer/index.tsx
  src/screens/Home/components/AppDrawer/useStyles.ts
  src/screens/Home/index.tsx
  src/screens/ImportAccountSelectChain/index.tsx
  src/screens/Landing/index.tsx
  src/screens/Landing/useStyles.ts
  src/screens/ManageStaking/index.tsx
  src/screens/ManageStaking/tabs/Restaking/index.tsx
  src/screens/ManageStaking/tabs/Restaking/useStyles.ts
  src/screens/ManageStaking/tabs/Staked/index.tsx
  src/screens/ManageStaking/tabs/Staked/useStyles.ts
  src/screens/ManageStaking/tabs/Unbonding/index.tsx
  src/screens/ManageStaking/tabs/Unbonding/useStyles.ts
  src/screens/Profile/index.tsx
  src/screens/Profile/useStyles.ts
  src/screens/ScanQr/components/QrCodeScanner/index.tsx
  src/screens/ScanQr/components/QrCodeScanner/useStyles.ts
  src/screens/ScanQr/index.tsx
  src/screens/Settings/index.tsx
  src/screens/SettingsChangeWalletPassword/index.tsx
  src/screens/SettingsChangeWalletPassword/useStyles.ts
  src/screens/SettingsDisplayMode/index.tsx
  src/screens/SettingsSwitchChain/index.tsx
  src/screens/SplashScreen/index.tsx
  src/screens/SplashScreen/useStyles.ts
  src/screens/Stake/index.tsx
  src/screens/ValidatorDetails/index.tsx
  src/screens/ValidatorDetails/useStyles.ts
  src/screens/WalletConnectSessions/index.tsx
  yarn.lock
Labels: Type: Enhancement, C: UI, P: iOS, automerge

#262 feat: improve staking related UI
  src/assets/locales/en/common.json
  src/assets/locales/en/staking.json
  src/hooks/staking/useTotalRedelegatingAmount.ts
  src/screens/ManageStaking/tabs/Restaking/components/RedelegationListItem/index.tsx
  src/screens/ManageStaking/tabs/Restaking/components/RedelegationListItem/useStyles.ts
  src/screens/ManageStaking/tabs/Unbonding/components/UnbondingDelegationListItem/index.tsx
  src/screens/ValidatorStakingInfo/components/RestakeToItem/index.tsx
  src/screens/ValidatorStakingInfo/components/RestakeToItem/useStyles.ts
  src/screens/ValidatorStakingInfo/components/UnbondingDelegationItem/index.tsx
  src/screens/ValidatorStakingInfo/components/UnbondingDelegationItem/useStyles.ts
  src/screens/ValidatorStakingInfo/index.tsx
Labels: Type: Enhancement, C: UI, automerge

#263 feat: use a default memo if the user didn't provide a custom one
  src/hooks/useBroadcastTx.ts
Labels: Type: Enhancement, C: Logic, automerge

#264 chore: update redelegate texts
  src/assets/locales/en/restaking.json
  src/assets/locales/en/staking.json
Labels: C: UI, automerge

#265 feat: update usePaginatedData hook
  src/hooks/usePaginatedData.ts
  src/screens/ScanQr/components/QrCodeScanner/index.tsx
  src/screens/SelectAccount/components/AccountPicker/useHooks.ts
  src/screens/SelectValidator/index.tsx
  src/screens/SendTokens/components/RecipientsList/hooks.ts
Labels: C: Logic, automerge

#268 fix(ios): send input visualization after pasting and address on iOS
  src/components/TextInput/useStyles.ts
  src/screens/ImportAccountFromMnemonic/index.tsx
  src/screens/ImportAccountFromMnemonic/useStyles.ts
  src/screens/Stake/index.tsx
  src/screens/Stake/useStyles.ts
Labels: Type: Bug, C: UI, P: iOS, automerge
